# Change these first
owner: AToska21 # Your GitHub organization or username, where this repository lives
repo: monocord # The name of this repository

sites:
  - name: Monocord
    url: https://chat.natsuki.live
  - name: Monogit
    url: https://git.natsuki.live
assignees: # Users to assign downtime issues (optional)
  - AToska21
  - ShadowMilky

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.natsuki.live
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.discordapp.com/avatars/642259365440520192/a478f3fcadc0841ad3213f413003f794.png?size=1024
  name: MonoSoftware
  introTitle: "**MonoSoftware** Welcome to MonoSoftware! This is a hub for software by the legend, Monomouse himself!"
  introMessage: "**MonoSoftware** This is the status page for MonoSoftware websites!"
  navbar:
    - title: Status
      href: /
    - title: Main
      href: https://chat.natsuki.live
    - title: Git
      href: https://git.natsuki.live

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
